#!/usr/bin/env bash
# Generates dist/install.sh — a FULLY SELF-CONTAINED J.A.R.V.I.S. installer
# with every project file embedded as base64. Run: ./build_installer.sh
set -euo pipefail
cd "$(dirname "$0")"

OUT="dist/install.sh"
mkdir -p dist
DELIM='JARVIS_B64_END_9f8e7d6c'

{
  printf '#!/usr/bin/env bash\n'
  printf '# J.A.R.V.I.S. self-contained installer — GENERATED by build_installer.sh. Do not edit by hand.\n'
  printf 'set -euo pipefail\n\n'
  printf '# ================= embedded project files =================\n'
  while IFS= read -r spec; do
    [ -z "$spec" ] && continue
    src="${spec%%:*}"
    dest="${spec##*:}"
    dir="$(dirname "$dest")"
    printf 'mkdir -p "%s"\n' "$dir"
    printf "base64 -d > \"%s\" <<'%s'\n" "$dest" "$DELIM"
    base64 "$src"
    printf '%s\n\n' "$DELIM"
  done <<'SPECS'
app/__init__.py:/opt/jarvis/app/__init__.py
app/main.py:/opt/jarvis/app/main.py
app/brain.py:/opt/jarvis/app/brain.py
app/tools.py:/opt/jarvis/app/tools.py
app/memory.py:/opt/jarvis/app/memory.py
app/voice.py:/opt/jarvis/app/voice.py
static/index.html:/opt/jarvis/static/index.html
requirements.txt:/opt/jarvis/requirements.txt
jarvis.service:/opt/jarvis/jarvis.service
jarvis-tunnel.service:/opt/jarvis/jarvis-tunnel.service
SPECS
  printf '# ================= installer body =================\n'
} > "$OUT"

cat >> "$OUT" <<'INSTALLER_BODY_EOF'

# ---- require root ----
if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: run this installer as root (e.g. sudo bash install.sh)" >&2
  exit 1
fi
export DEBIAN_FRONTEND=noninteractive

echo "[1/8] Installing system packages..."
apt-get update -qq
apt-get install -y -qq python3-venv ffmpeg curl ca-certificates openssl

echo "[2/8] Creating jarvis system user..."
id jarvis >/dev/null 2>&1 || useradd -r -m -s /bin/false jarvis
mkdir -p /opt/jarvis/data
chown -R jarvis:jarvis /opt/jarvis

echo "[3/8] Creating Python venv and installing dependencies (a few minutes)..."
if [ ! -x /opt/jarvis/venv/bin/python ]; then
  python3 -m venv /opt/jarvis/venv
fi
/opt/jarvis/venv/bin/pip install -q --upgrade pip
/opt/jarvis/venv/bin/pip install -q -r /opt/jarvis/requirements.txt
chown -R jarvis:jarvis /opt/jarvis

echo "[4/8] Writing /etc/jarvis.env ..."
if [ ! -f /etc/jarvis.env ]; then
  GROQ_KEY=""
  read -s -r -p "Groq API key (free at https://groq.com — Enter to skip, add later): " GROQ_KEY </dev/tty || GROQ_KEY=""
  echo
  JARVIS_TOKEN="$(openssl rand -hex 32)"
  {
    echo "GROQ_API_KEY=${GROQ_KEY}"
    echo "JARVIS_TOKEN=${JARVIS_TOKEN}"
    echo "JARVIS_DATA_DIR=/opt/jarvis/data"
  } > /etc/jarvis.env
  chmod 600 /etc/jarvis.env
  chown jarvis:jarvis /etc/jarvis.env
  echo "      (new random phone token generated)"
else
  echo "      /etc/jarvis.env already exists — keeping it (re-run safe)."
fi

echo "[5/8] Installing cloudflared (quick tunnel)..."
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64)        CFARCH=amd64 ;;
  aarch64|arm64) CFARCH=arm64 ;;
  *) echo "ERROR: unsupported architecture: $ARCH" >&2; exit 1 ;;
esac
if [ ! -x /usr/local/bin/cloudflared ]; then
  curl -fsSL -o /usr/local/bin/cloudflared \
    "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-${CFARCH}"
  chmod +x /usr/local/bin/cloudflared
else
  echo "      cloudflared already installed."
fi

echo "[6/8] Installing systemd units..."
cp /opt/jarvis/jarvis.service /etc/systemd/system/jarvis.service
cp /opt/jarvis/jarvis-tunnel.service /etc/systemd/system/jarvis-tunnel.service
systemctl daemon-reload
systemctl enable --now jarvis.service
systemctl enable --now jarvis-tunnel.service

echo "[7/8] Waiting for the tunnel to come up..."
sleep 8
URL="$(journalctl -u jarvis-tunnel --no-pager -n 40 2>/dev/null | grep -o 'https://[^ ]*trycloudflare.com' | head -n 1 || true)"

echo "[8/8] Done."
echo "=================================================================="
if [ -n "${URL:-}" ]; then
  echo "  Open on your phone:  $URL"
else
  echo "  Tunnel URL not captured yet — run:"
  echo "    journalctl -u jarvis-tunnel --no-pager -n 40 | grep -o 'https://[^ ]*trycloudflare.com'"
fi
echo "  Your phone token (paste into the app, tap Save):"
echo -n "    "
grep '^JARVIS_TOKEN=' /etc/jarvis.env | cut -d= -f2
echo ""
echo "  Then: hold the mic button, speak, release. Jarvis answers out loud."
echo ""
echo "  No Groq key yet? Add one any time:"
echo "    sudo nano /etc/jarvis.env   # set GROQ_API_KEY=..."
echo "    sudo systemctl restart jarvis"
echo "=================================================================="
INSTALLER_BODY_EOF

chmod +x "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
